"""Phase 0.11.e.3 — ADR template scaffolding + content 검증 (ADR 0011 §1.3 D6).

`trading proposal approve <id>` 호출 시 ADR template 자동 생성 — 사람이
본문 채워야 minimum 필드 충족 후 ADR_FILED 전이.

D6 "ADR 자동 template scaffolding" 하이브리드 정합:
    - 최소 필드 검증 = (a) ADR 번호 박제 + (b) supersede 대상 + (c)
      reasoning 비어있지 않음.
    - 검증 방식 = `<TBD: ...>` placeholder 잔존 zero. 즉 template 의
      `<TBD>` marker 모두 사람이 실제 내용으로 교체해야 ADR_FILED 전이
      가능.

`_render_adr_template` — Proposal 정보 + 사용자 지정 ADR 번호 → markdown.
`_verify_adr_content` — 파일 내용 검사 (TBD 부재 + 최소 길이).

Lifecycle: 5th ring 영구 유지 (D13).
Underscore-prefix private (`__all__ = []`).
"""
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

    from src.research.dynamic_adjustment._proposal import _Proposal


__all__: list[str] = []


# 최소 ADR 길이 — template 보다 크게 (사람이 본문 추가 강제).
_MIN_ADR_CONTENT_BYTES = 2000

# Template placeholder marker — verification 대상.
_TBD_MARKER = "<TBD"


def _render_adr_template(
    proposal: _Proposal,
    *,
    adr_number: str,
    supersedes: str | None = None,
) -> str:
    """`approve` 호출 시 ADR template 마크다운 생성.

    Args:
        proposal: 승인된 proposal.
        adr_number: ADR 번호 (예: "ADR-0099" 또는 "0099"). Caller 가 next
            available 번호 결정.
        supersedes: supersede 대상 ADR 식별자 (예: "ADR 0003 §19.4"). None
            시 `<TBD>` 박제.

    Returns:
        Markdown 문자열 — `<TBD>` placeholder 잔존 (사람이 채워야 함).
    """
    change = proposal.proposed_change
    supersede_block = supersedes if supersedes else "<TBD: supersede target>"
    return f"""# {adr_number} — Dynamic Adjustment Proposal {proposal.proposal_id}

> **Status**: ADR template scaffolded — 사람이 본문 채운 후 `proposal verify-adr` 호출.
> **Date**: <TBD: YYYY-MM-DD>
> **Supersedes**: {supersede_block}
> **Generated by**: ADR 0011 §1.3 D6 auto-template scaffolding (sub-step 0.11.e.3).
> **Proposal id**: `{proposal.proposal_id}`
> **Trigger**: `{proposal.trigger_signal.value}`
> **Proposed change**: `{change.proposal_type.value}` on target `{change.target}` ({change.from_value} → {change.to_value})

---

## 1. Background

<TBD: 본 ADR 의 배경 — 어떤 결정 라운드 / 어떤 trigger 가 본 변경 제안을 도출했는지>

## 2. Decision

<TBD: 채택된 결정 — 변경 내용 verbatim + supersede 시점>

## 3. Reasoning

<TBD: 결정 근거 — backtest 결과 / OOS metric / 사용자 spec confirmation 인용>

### 3.1 Trigger 평가 정본

- Trigger signal: `{proposal.trigger_signal.value}`
- Proposal id: `{proposal.proposal_id}`
- Created at: `{proposal.created_at.isoformat()}`
- Current state snapshot (verbatim):

```json
{proposal.current_state_snapshot}
```

### 3.2 Proposed change (verbatim)

- Type: `{change.proposal_type.value}`
- Target: `{change.target}`
- From: `{change.from_value}`
- To: `{change.to_value}`
- Delta percent: `{change.delta_pct}`
- Rationale (proposal 시점): `{change.rationale}`

## 4. Consequences

<TBD: 본 변경의 결과 — 회귀 invariant 영향 / 후속 phase trigger 조건 / 회복 절차>

## 5. Verification

- ADR 0011 §1.6 #4 invariant: 본 ADR 박제 후 `proposal verify-adr {proposal.proposal_id}` 명령으로 APPROVED → ADR_FILED 전이.
- ADR 0011 §1.6 #1 invariant: ADR_FILED → APPLIED 전이는 다음 cron 실행 시 자동 pickup.
- 회귀 invariant 보존 검증 (Phase 0.7.3 baseline / namespace / mypy):

```bash
bash scripts/check_namespace.sh
uv run mypy src/research/dynamic_adjustment/
uv run pytest tests/research/dynamic_adjustment/ -q --no-cov
```

## 6. References

- ADR 0011 (Phase 0.11.e Dynamic Adjustment Proposal Engine) §1.3 D6.
- Proposal reasoning_json: 본 ADR §3.3 영역 (verbatim 박제 의무).
- CLAUDE.md §7.1 — 모든 의사결정 reasoning JSON 보존.

### 3.3 Reasoning JSON (verbatim)

```json
{proposal.reasoning_json}
```

---

**본 ADR template scaffolded by sub-step 0.11.e.3 — 사람이 모든 placeholder 를 실제 내용으로 교체 후 `proposal verify-adr` 호출 시 file_exists + content 검증 후 APPROVED → ADR_FILED 전이.**
"""


def _verify_adr_content(adr_path: Path) -> tuple[bool, str]:
    """ADR 파일 내용 검증 — TBD marker 부재 + 최소 길이.

    Args:
        adr_path: ADR 파일 경로.

    Returns:
        `(verified, message)` — verified=True 시 APPROVED→ADR_FILED 전이
        가능. message 는 verified=False 시 사유.
    """
    if not adr_path.exists():
        return False, f"ADR file does not exist: {adr_path}"
    content = adr_path.read_text(encoding="utf-8")
    if len(content.encode("utf-8")) < _MIN_ADR_CONTENT_BYTES:
        return (
            False,
            f"ADR content too short — {len(content.encode('utf-8'))} bytes < "
            f"{_MIN_ADR_CONTENT_BYTES} threshold. 사람이 본문 채워야 함.",
        )
    if _TBD_MARKER in content:
        # Count TBD markers for diagnostic
        count = content.count(_TBD_MARKER)
        return (
            False,
            f"ADR contains {count} unresolved `<TBD>` markers — 사람이 모두 "
            f"실제 내용으로 교체해야 함.",
        )
    return True, "ADR content verified (no TBD markers + content >= threshold)."
